import os
os.system('cls')

print('Boas vindas ao nosso glorioso jogo de MadLib')
substantivo = input('Digite um nome: ')
adjetivo = input('Digite um adjetivo: ')
verbo = input('Digite um verbo: ')
objeto = input('Diga um objeto: ')
profissao = input('Diga uma profissão: ')
adjetivo2 = input('Diga um adjetivo: ')
numero = input('Diga um número: ')
animal = input ('Diga um animal: ')
objeto2 = input('Diga um objeto: ')
objeto3 = input('Diga um objeto: ')

print()
print("A Grande Aventura no Escritório de Tecnologia")
print()
print("Um dia, o " + substantivo + " estava trabalhando em um projeto super " + adjetivo + ". De repente, o computador começou a " + verbo + " sozinho!")
print("Sem pensar duas vezes, o(a) " + substantivo + " pegou seu " + objeto + " e começou a digitar comandos como um(a) verdadeiro(a) " + profissao + ".")
print('"Preciso consertar isso antes que o sistema fique ' + adjetivo2 + '!" exclamou o(a) ' + substantivo + '. Depois de ' + numero + ' tentativas, finalmente o computador respondeu: ')
print('"O problema foi causado por um ' + animal + ' que estava no sistema!"')
print('Com isso, o problema foi resolvido, e o(a) ' + substantivo + ' ganhou o prêmio de ' + objeto2 + 'mais inovador do ano.')
print('Moral da história: sempre leve seu ' + objeto3 + ' para o escritório, porque nunca se sabe quando você vai precisar!')

